---
title: "Graficos"
author: "Santiago Pérez Moncada"
date: "16/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Graficos con la funcion `plot`

```{r primer_plot, fig.cap="Grafico basico", fig.align='center'}
x = c(2,6,7,8,-1)
y = c(1,6,8,-3,5)
plot(x,y)
```

Si no incorporamos vector `y`, `R` nos va a tomar el parametro `x`
como si fuese el vector de datos `y`

```{r}
plot(2^(1:6))
```

Si queremos representar una funcion $f(x)$
```{r}
f <- function(x){sqrt(x)}
plot(f)
```

## Escala logaritmica
```{r fig.align='center'}
par(mfrow = c(1,2))

plot = plot(exp(1:20), xlab = 'Indice', ylab = expression(e^{1:20}),
            main = "Escala lineal")


plotLog = plot(exp(1:20),log = "y" ,xlab = 'Indice', ylab = expression(e^{1:20}),
            main = "Escala Logaritmica")
```

## Parametros
```{r echo=FALSE, fig.align='center'}
n = 1:20

fib = (1/sqrt(5))*((1+sqrt(5))/2)^n - (1/sqrt(5))*((1-sqrt(5))/2)^n

plot(fib, xlab="n", ylab = expression(F[n]),
     main="Susecion de fibonacci", pch = 21, cex=2,
     col="red2", bg="purple", log="xy")
```

## Tipos de graficos
```{r fig.align='center'}
par(mfrow=c(3,2))

x = c(50:59)
y = c(2,9,25,2,100,77,62,54,19,40)

plot(x,y, pch=23, cex=2, col="blue",type="p")
plot(x,y, pch=23, cex=2, col="blueviolet",type="l")
plot(x,y, pch=23, cex=2, col="gold",type="b")
plot(x,y, pch=23, cex=2, col="deeppink",type="o")
plot(x,y, pch=23, cex=2, col="springgreen",type="h")
plot(x,y, pch=23, cex=2, col="firebrick1",type="s")

par(mfrow=c(1,1))
```


```{r}
plot(n, fib, pch=21, col="red", bg="yellow", cex=1.2,
     main="Fibonacci",
     type="o", lty="dotted", lwd=2,
     xlim=c(1,10), ylim = c(1,100),
     xaxp= c(1,10,3), yaxp = c(0,100,10))
```

## Añadiendo elementos al grafico
```{r}
x = (2*(1:20))
y = (-1)^(1:20)*5*(1:20)

plot(x,y, main="Poniendo un punto y una recta",
     pch=8,cex=1,type="b", lty=4,
     lwd=4, xaxp=c(0,40,2), yaxp=c(-100,100,8))

points(20,0,col="red", cex=4, pch=16)
abline(h=0,lty=2,col="dodgerblue")
```

```{r}
f <- function(x){
  x^2 - 2*x + sqrt(abs(x))
}

plot(f, xlim = c(-3,3))
points(0,0, pch=19)
points(-3:3, (-3:3)^2,col="blue")
abline(2,3, lty= "dashed", col="red")
abline(v=2, lty= "dotted", col="green")
abline(h=5, lty= "dotdash", col="purple")
```

```{r}
f <- function(x){x^2}
plot(f, xlim=c(-3,3), col="red", lwd=2,xlab="x",ylab=expression(x^2))
abline(h=0:9, v=-3:3, lty="dotted", col="grey")

```

```{r}
plot(tan, xlim=c(-pi,pi), ylim=c(-5,5))
abline(v=c(-pi/2, pi/2), col="red")
```

## Añadiendo Etiquetas
```{r}
alumnos = c(1:10)
notas = c(2,5,7,9,8,3,5,6,10,7)
plot(alumnos, notas, main="Grafico con texto")
text(alumnos,notas, labels=c("S","A","N","E","N","S","A","A","A","E","N"),
     pos = c(rep(3,times=8),1,3) )
```

```{r}
plot(0,0)
text(0,0,labels = "debajo",pos=1)
text(0,0,labels = "izquierda",pos=2)
text(0,0,labels = "arrba",pos=3)
text(0,0,labels = "derecha",pos=4)
point
text(0,0,labels = "centro")

```

```{r}
f <- function(x){x^2}

plot(f, xlim = c(-3,3), ylim=c(-10,10))
points(-3:3, f(-3:3), pch=19)
lines(-3:3, f(-3:3), lwd =2,lty="dotted", col="red")
curve(x^3, lty="dashed", col="blue", add=TRUE)
curve(x^4,col="purple", add=TRUE)

legend("bottomright",
       legend = c(expression(x^2),expression(x^3),expression(x^4)),
       lwd=2, 
       col=c("red","blue","purple"),
       lty=c("dotted","dashed","dashed"))
```

## Añadiendo leyendas
```{r}
x = seq(0,2*pi,0.1)
plot(x,sin(x),type="l",col="blue",lwd=3, xlab="", ylab="")
lines(x,cos(x),col="green",lwd=3)
lines(x,tan(x),col="purple",lwd=3)

legend("bottomleft",col=c("blue","green","purple"),
       legend = c("Seno","Coseno","Tangente"),
       lwd=3, bty="l")

```

```{r}
y <- function(x){x^2-3*x+30}
plot(y(-15:15),
     main="Una parabola",
     xlab= expression(x),
     ylab=expression(x^2-3*x+30))
```

